# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racerapp.Race'),
        ),
    ]
